//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maham.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Maham.Resources.AppResource.ar", typeof(AppResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string emailtext {
            get {
                return ResourceManager.GetString("emailtext", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string passwordtext {
            get {
                return ResourceManager.GetString("passwordtext", resourceCulture);
            }
        }
        
        public static string tasknametext {
            get {
                return ResourceManager.GetString("tasknametext", resourceCulture);
            }
        }
        
        public static string urgentsupporttext {
            get {
                return ResourceManager.GetString("urgentsupporttext", resourceCulture);
            }
        }
        
        public static string urgentsupporttext2 {
            get {
                return ResourceManager.GetString("urgentsupporttext2", resourceCulture);
            }
        }
        
        public static string assigntotext {
            get {
                return ResourceManager.GetString("assigntotext", resourceCulture);
            }
        }
        
        public static string browsfiletext {
            get {
                return ResourceManager.GetString("browsfiletext", resourceCulture);
            }
        }
        
        public static string buttonaddtext {
            get {
                return ResourceManager.GetString("buttonaddtext", resourceCulture);
            }
        }
        
        public static string buttoncleartext {
            get {
                return ResourceManager.GetString("buttoncleartext", resourceCulture);
            }
        }
        
        public static string descriptiontext {
            get {
                return ResourceManager.GetString("descriptiontext", resourceCulture);
            }
        }
        
        public static string enddatetext {
            get {
                return ResourceManager.GetString("enddatetext", resourceCulture);
            }
        }
        
        public static string enterresponsiblenametext {
            get {
                return ResourceManager.GetString("enterresponsiblenametext", resourceCulture);
            }
        }
        
        public static string filestext {
            get {
                return ResourceManager.GetString("filestext", resourceCulture);
            }
        }
        
        public static string indicatorloadingtext {
            get {
                return ResourceManager.GetString("indicatorloadingtext", resourceCulture);
            }
        }
        
        public static string prioritytext {
            get {
                return ResourceManager.GetString("prioritytext", resourceCulture);
            }
        }
        
        public static string referencestext {
            get {
                return ResourceManager.GetString("referencestext", resourceCulture);
            }
        }
        
        public static string showmoretext {
            get {
                return ResourceManager.GetString("showmoretext", resourceCulture);
            }
        }
        
        public static string startdatetext {
            get {
                return ResourceManager.GetString("startdatetext", resourceCulture);
            }
        }
        
        public static string crtiticlenumtext {
            get {
                return ResourceManager.GetString("crtiticlenumtext", resourceCulture);
            }
        }
        
        public static string highenumtext {
            get {
                return ResourceManager.GetString("highenumtext", resourceCulture);
            }
        }
        
        public static string lowenumtext {
            get {
                return ResourceManager.GetString("lowenumtext", resourceCulture);
            }
        }
        
        public static string normalenumtext {
            get {
                return ResourceManager.GetString("normalenumtext", resourceCulture);
            }
        }
        
        public static string entertasknameplaceholder {
            get {
                return ResourceManager.GetString("entertasknameplaceholder", resourceCulture);
            }
        }
        
        public static string deletebuttontext {
            get {
                return ResourceManager.GetString("deletebuttontext", resourceCulture);
            }
        }
        
        public static string deletetasktext2popup {
            get {
                return ResourceManager.GetString("deletetasktext2popup", resourceCulture);
            }
        }
        
        public static string deletetasktextpopup {
            get {
                return ResourceManager.GetString("deletetasktextpopup", resourceCulture);
            }
        }
        
        public static string detettaskpopuptext {
            get {
                return ResourceManager.GetString("detettaskpopuptext", resourceCulture);
            }
        }
        
        public static string discardtext {
            get {
                return ResourceManager.GetString("discardtext", resourceCulture);
            }
        }
        
        public static string addtextalerttitle {
            get {
                return ResourceManager.GetString("addtextalerttitle", resourceCulture);
            }
        }
        
        public static string alertfilledalldata {
            get {
                return ResourceManager.GetString("alertfilledalldata", resourceCulture);
            }
        }
        
        public static string alerttext {
            get {
                return ResourceManager.GetString("alerttext", resourceCulture);
            }
        }
        
        public static string canceltext {
            get {
                return ResourceManager.GetString("canceltext", resourceCulture);
            }
        }
        
        public static string choosereftext {
            get {
                return ResourceManager.GetString("choosereftext", resourceCulture);
            }
        }
        
        public static string failuretext {
            get {
                return ResourceManager.GetString("failuretext", resourceCulture);
            }
        }
        
        public static string filenametext {
            get {
                return ResourceManager.GetString("filenametext", resourceCulture);
            }
        }
        
        public static string nofiletext {
            get {
                return ResourceManager.GetString("nofiletext", resourceCulture);
            }
        }
        
        public static string oktext {
            get {
                return ResourceManager.GetString("oktext", resourceCulture);
            }
        }
        
        public static string taskaddedtext {
            get {
                return ResourceManager.GetString("taskaddedtext", resourceCulture);
            }
        }
        
        public static string tasknotadded {
            get {
                return ResourceManager.GetString("tasknotadded", resourceCulture);
            }
        }
        
        public static string uploadagintext {
            get {
                return ResourceManager.GetString("uploadagintext", resourceCulture);
            }
        }
        
        public static string uploadfileagaintext {
            get {
                return ResourceManager.GetString("uploadfileagaintext", resourceCulture);
            }
        }
        
        public static string newtasktitle {
            get {
                return ResourceManager.GetString("newtasktitle", resourceCulture);
            }
        }
        
        public static string notificationsettingtext {
            get {
                return ResourceManager.GetString("notificationsettingtext", resourceCulture);
            }
        }
        
        public static string profilesettingtext {
            get {
                return ResourceManager.GetString("profilesettingtext", resourceCulture);
            }
        }
        
        public static string logouttext {
            get {
                return ResourceManager.GetString("logouttext", resourceCulture);
            }
        }
        
        public static string edittasksuccesstext {
            get {
                return ResourceManager.GetString("edittasksuccesstext", resourceCulture);
            }
        }
        
        public static string edittaskfailuretext {
            get {
                return ResourceManager.GetString("edittaskfailuretext", resourceCulture);
            }
        }
        
        public static string edittasktitle {
            get {
                return ResourceManager.GetString("edittasktitle", resourceCulture);
            }
        }
        
        public static string closedtext {
            get {
                return ResourceManager.GetString("closedtext", resourceCulture);
            }
        }
        
        public static string returnedtext {
            get {
                return ResourceManager.GetString("returnedtext", resourceCulture);
            }
        }
        
        public static string commentstask {
            get {
                return ResourceManager.GetString("commentstask", resourceCulture);
            }
        }
        
        public static string Comparedatetext {
            get {
                return ResourceManager.GetString("Comparedatetext", resourceCulture);
            }
        }
        
        public static string Editbutton {
            get {
                return ResourceManager.GetString("Editbutton", resourceCulture);
            }
        }
        
        public static string invailddate {
            get {
                return ResourceManager.GetString("invailddate", resourceCulture);
            }
        }
        
        public static string addcommentbutton {
            get {
                return ResourceManager.GetString("addcommentbutton", resourceCulture);
            }
        }
        
        public static string addcommentfail {
            get {
                return ResourceManager.GetString("addcommentfail", resourceCulture);
            }
        }
        
        public static string inProgressTask {
            get {
                return ResourceManager.GetString("inProgressTask", resourceCulture);
            }
        }
        
        public static string notStartedTask {
            get {
                return ResourceManager.GetString("notStartedTask", resourceCulture);
            }
        }
        
        public static string returnedTask {
            get {
                return ResourceManager.GetString("returnedTask", resourceCulture);
            }
        }
        
        public static string startdatetext1 {
            get {
                return ResourceManager.GetString("startdatetext1", resourceCulture);
            }
        }
        
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        public static string NoNewNotificationsLabel {
            get {
                return ResourceManager.GetString("NoNewNotificationsLabel", resourceCulture);
            }
        }
        
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        public static string WaltDesinyLabel {
            get {
                return ResourceManager.GetString("WaltDesinyLabel", resourceCulture);
            }
        }
        
        public static string CommenttextMessage {
            get {
                return ResourceManager.GetString("CommenttextMessage", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        public static string DidnotStarted {
            get {
                return ResourceManager.GetString("DidnotStarted", resourceCulture);
            }
        }
        
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        public static string Statustext {
            get {
                return ResourceManager.GetString("Statustext", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        public static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        public static string ReassignText {
            get {
                return ResourceManager.GetString("ReassignText", resourceCulture);
            }
        }
        
        public static string CantReassignmessage {
            get {
                return ResourceManager.GetString("CantReassignmessage", resourceCulture);
            }
        }
        
        public static string ReassignSucess {
            get {
                return ResourceManager.GetString("ReassignSucess", resourceCulture);
            }
        }
        
        public static string Reassignsucessmessage {
            get {
                return ResourceManager.GetString("Reassignsucessmessage", resourceCulture);
            }
        }
        
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        public static string saerchplaceholder {
            get {
                return ResourceManager.GetString("saerchplaceholder", resourceCulture);
            }
        }
        
        public static string imageuploadfilled {
            get {
                return ResourceManager.GetString("imageuploadfilled", resourceCulture);
            }
        }
        
        public static string ResetMessageSucess {
            get {
                return ResourceManager.GetString("ResetMessageSucess", resourceCulture);
            }
        }
        
        public static string ResetmessageTitle {
            get {
                return ResourceManager.GetString("ResetmessageTitle", resourceCulture);
            }
        }
        
        public static string resetpassfail {
            get {
                return ResourceManager.GetString("resetpassfail", resourceCulture);
            }
        }
        
        public static string choosereassignemp {
            get {
                return ResourceManager.GetString("choosereassignemp", resourceCulture);
            }
        }
        
        public static string serachnamemessage {
            get {
                return ResourceManager.GetString("serachnamemessage", resourceCulture);
            }
        }
        
        public static string noreassignlist {
            get {
                return ResourceManager.GetString("noreassignlist", resourceCulture);
            }
        }
        
        public static string closequestion {
            get {
                return ResourceManager.GetString("closequestion", resourceCulture);
            }
        }
        
        public static string Resetpasstext {
            get {
                return ResourceManager.GetString("Resetpasstext", resourceCulture);
            }
        }
        
        public static string returnquestion {
            get {
                return ResourceManager.GetString("returnquestion", resourceCulture);
            }
        }
        
        public static string filiterpoptitile {
            get {
                return ResourceManager.GetString("filiterpoptitile", resourceCulture);
            }
        }
        
        public static string welcometext {
            get {
                return ResourceManager.GetString("welcometext", resourceCulture);
            }
        }
        
        public static string fromtext {
            get {
                return ResourceManager.GetString("fromtext", resourceCulture);
            }
        }
        
        public static string totext {
            get {
                return ResourceManager.GetString("totext", resourceCulture);
            }
        }
        
        public static string exisrcodeTitle {
            get {
                return ResourceManager.GetString("exisrcodeTitle", resourceCulture);
            }
        }
        
        public static string existcodebtn {
            get {
                return ResourceManager.GetString("existcodebtn", resourceCulture);
            }
        }
        
        public static string existcoetext {
            get {
                return ResourceManager.GetString("existcoetext", resourceCulture);
            }
        }
        
        public static string existclienttext {
            get {
                return ResourceManager.GetString("existclienttext", resourceCulture);
            }
        }
        
        public static string newClientText {
            get {
                return ResourceManager.GetString("newClientText", resourceCulture);
            }
        }
        
        public static string projecttext {
            get {
                return ResourceManager.GetString("projecttext", resourceCulture);
            }
        }
        
        public static string projectaletmessage {
            get {
                return ResourceManager.GetString("projectaletmessage", resourceCulture);
            }
        }
        
        public static string Sectortext {
            get {
                return ResourceManager.GetString("Sectortext", resourceCulture);
            }
        }
        
        public static string Assigneetext {
            get {
                return ResourceManager.GetString("Assigneetext", resourceCulture);
            }
        }
        
        public static string hidetext {
            get {
                return ResourceManager.GetString("hidetext", resourceCulture);
            }
        }
        
        public static string nametext {
            get {
                return ResourceManager.GetString("nametext", resourceCulture);
            }
        }
        
        public static string newpassplaceholder {
            get {
                return ResourceManager.GetString("newpassplaceholder", resourceCulture);
            }
        }
        
        public static string oldpasswordplaceholder {
            get {
                return ResourceManager.GetString("oldpasswordplaceholder", resourceCulture);
            }
        }
        
        public static string resetpalceholder {
            get {
                return ResourceManager.GetString("resetpalceholder", resourceCulture);
            }
        }
        
        public static string resetpasswordtext {
            get {
                return ResourceManager.GetString("resetpasswordtext", resourceCulture);
            }
        }
        
        public static string resetpasswordtext2 {
            get {
                return ResourceManager.GetString("resetpasswordtext2", resourceCulture);
            }
        }
        
        public static string showtext {
            get {
                return ResourceManager.GetString("showtext", resourceCulture);
            }
        }
        
        public static string saerchplaceholdertype2 {
            get {
                return ResourceManager.GetString("saerchplaceholdertype2", resourceCulture);
            }
        }
        
        public static string departmenttext {
            get {
                return ResourceManager.GetString("departmenttext", resourceCulture);
            }
        }
        
        public static string dowlnoadSucessfully {
            get {
                return ResourceManager.GetString("dowlnoadSucessfully", resourceCulture);
            }
        }
        
        public static string assignbutton {
            get {
                return ResourceManager.GetString("assignbutton", resourceCulture);
            }
        }
        
        public static string findemployeetext {
            get {
                return ResourceManager.GetString("findemployeetext", resourceCulture);
            }
        }
        
        public static string sourcetext {
            get {
                return ResourceManager.GetString("sourcetext", resourceCulture);
            }
        }
        
        public static string progressnotupdatedtext {
            get {
                return ResourceManager.GetString("progressnotupdatedtext", resourceCulture);
            }
        }
        
        public static string canreaasignpopuptext {
            get {
                return ResourceManager.GetString("canreaasignpopuptext", resourceCulture);
            }
        }
        
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        public static string taskDetals {
            get {
                return ResourceManager.GetString("taskDetals", resourceCulture);
            }
        }
        
        public static string taskDelayed {
            get {
                return ResourceManager.GetString("taskDelayed", resourceCulture);
            }
        }
        
        public static string ExistClient {
            get {
                return ResourceManager.GetString("ExistClient", resourceCulture);
            }
        }
        
        public static string noresultsearch {
            get {
                return ResourceManager.GetString("noresultsearch", resourceCulture);
            }
        }
        
        public static string communitynameplceholder {
            get {
                return ResourceManager.GetString("communitynameplceholder", resourceCulture);
            }
        }
        
        public static string comunitynametext {
            get {
                return ResourceManager.GetString("comunitynametext", resourceCulture);
            }
        }
        
        public static string emailtextnew {
            get {
                return ResourceManager.GetString("emailtextnew", resourceCulture);
            }
        }
        
        public static string phonenumberplaceholder {
            get {
                return ResourceManager.GetString("phonenumberplaceholder", resourceCulture);
            }
        }
        
        public static string phonenumbertext {
            get {
                return ResourceManager.GetString("phonenumbertext", resourceCulture);
            }
        }
        
        public static string submittext {
            get {
                return ResourceManager.GetString("submittext", resourceCulture);
            }
        }
        
        public static string usernameplaceholder {
            get {
                return ResourceManager.GetString("usernameplaceholder", resourceCulture);
            }
        }
        
        public static string usernametext {
            get {
                return ResourceManager.GetString("usernametext", resourceCulture);
            }
        }
    }
}
