//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maham.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maham.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Comment.
        /// </summary>
        public static string addcommentbutton {
            get {
                return ResourceManager.GetString("addcommentbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong Happened In Add Comment.
        /// </summary>
        public static string addcommentfail {
            get {
                return ResourceManager.GetString("addcommentfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string addtextalerttitle {
            get {
                return ResourceManager.GetString("addtextalerttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Missing Filled.
        /// </summary>
        public static string alertfilledalldata {
            get {
                return ResourceManager.GetString("alertfilledalldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string alerttext {
            get {
                return ResourceManager.GetString("alerttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Notifications.
        /// </summary>
        public static string AllowPushNotification {
            get {
                return ResourceManager.GetString("AllowPushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string arabic {
            get {
                return ResourceManager.GetString("arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Project You Should Only Assign To Yourself.
        /// </summary>
        public static string assignalerttext {
            get {
                return ResourceManager.GetString("assignalerttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Employee.
        /// </summary>
        public static string assignbutton {
            get {
                return ResourceManager.GetString("assignbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assigneetext {
            get {
                return ResourceManager.GetString("Assigneetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string assigntotext {
            get {
                return ResourceManager.GetString("assigntotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As User.
        /// </summary>
        public static string asuser {
            get {
                return ResourceManager.GetString("asuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As User Group.
        /// </summary>
        public static string asusergroup {
            get {
                return ResourceManager.GetString("asusergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Files To Upload.
        /// </summary>
        public static string browsfiletext {
            get {
                return ResourceManager.GetString("browsfiletext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit-department.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string buttonaddtext {
            get {
                return ResourceManager.GetString("buttonaddtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string buttoncleartext {
            get {
                return ResourceManager.GetString("buttoncleartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string canceltext {
            get {
                return ResourceManager.GetString("canceltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Reassign Task .
        /// </summary>
        public static string canreaasignpopuptext {
            get {
                return ResourceManager.GetString("canreaasignpopuptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Reassign Employee.
        /// </summary>
        public static string CantReassignmessage {
            get {
                return ResourceManager.GetString("CantReassignmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Due Date Request.
        /// </summary>
        public static string ChangeDueDateRequesttxt {
            get {
                return ResourceManager.GetString("ChangeDueDateRequesttxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have To Choose Employee First.
        /// </summary>
        public static string choosereassignemp {
            get {
                return ResourceManager.GetString("choosereassignemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Reference.
        /// </summary>
        public static string choosereftext {
            get {
                return ResourceManager.GetString("choosereftext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Source.
        /// </summary>
        public static string ChooseSource {
            get {
                return ResourceManager.GetString("ChooseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Tasks Mode:.
        /// </summary>
        public static string ChooseTasksMode {
            get {
                return ResourceManager.GetString("ChooseTasksMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string closedTask {
            get {
                return ResourceManager.GetString("closedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  completed Tasks Lists.
        /// </summary>
        public static string ClosedTasksLists {
            get {
                return ResourceManager.GetString("ClosedTasksLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closedtext {
            get {
                return ResourceManager.GetString("closedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Complete.
        /// </summary>
        public static string closequestion {
            get {
                return ResourceManager.GetString("closequestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string commentstask {
            get {
                return ResourceManager.GetString("commentstask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Can&apos;t Be Empty.
        /// </summary>
        public static string CommenttextMessage {
            get {
                return ResourceManager.GetString("CommenttextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Community Name.
        /// </summary>
        public static string communitynameplceholder {
            get {
                return ResourceManager.GetString("communitynameplceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Should Be Greater Than Start Date.
        /// </summary>
        public static string Comparedatetext {
            get {
                return ResourceManager.GetString("Comparedatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Request.
        /// </summary>
        public static string completedTask {
            get {
                return ResourceManager.GetString("completedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string completeText {
            get {
                return ResourceManager.GetString("completeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Name.
        /// </summary>
        public static string comunitynametext {
            get {
                return ResourceManager.GetString("comunitynametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong, App Restarted, And  A Report Sent To Administrator.
        /// </summary>
        public static string CrashMessage {
            get {
                return ResourceManager.GetString("CrashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string crtiticlenumtext {
            get {
                return ResourceManager.GetString("crtiticlenumtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        public static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletebuttontext {
            get {
                return ResourceManager.GetString("deletebuttontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete?.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tasks List.
        /// </summary>
        public static string deletetasktext2popup {
            get {
                return ResourceManager.GetString("deletetasktext2popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Deleting This Task, It Will Not Appear In Your Tasks List.
        /// </summary>
        public static string deletetasktextpopup {
            get {
                return ResourceManager.GetString("deletetasktextpopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string departmenttext {
            get {
                return ResourceManager.GetString("departmenttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descriptiontext {
            get {
                return ResourceManager.GetString("descriptiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        public static string detettaskpopuptext {
            get {
                return ResourceManager.GetString("detettaskpopuptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string DidnotStarted {
            get {
                return ResourceManager.GetString("DidnotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string discardtext {
            get {
                return ResourceManager.GetString("discardtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully Downloaded.
        /// </summary>
        public static string dowlnoadSucessfully {
            get {
                return ResourceManager.GetString("dowlnoadSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Shouldn&apos;t Be Smaller Than Now.
        /// </summary>
        public static string DueDate_Now {
            get {
                return ResourceManager.GetString("DueDate_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Shouldn&apos;t Be Smaller Than Start Date.
        /// </summary>
        public static string DueDate_StartDate {
            get {
                return ResourceManager.GetString("DueDate_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Due Date.
        /// </summary>
        public static string DueDateRequired {
            get {
                return ResourceManager.GetString("DueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Editbutton {
            get {
                return ResourceManager.GetString("Editbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong In Edit Task.
        /// </summary>
        public static string edittaskfailuretext {
            get {
                return ResourceManager.GetString("edittaskfailuretext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Edited Successfully .
        /// </summary>
        public static string edittasksuccesstext {
            get {
                return ResourceManager.GetString("edittasksuccesstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string edittasktitle {
            get {
                return ResourceManager.GetString("edittasktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string emailtext {
            get {
                return ResourceManager.GetString("emailtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string emailtextnew {
            get {
                return ResourceManager.GetString("emailtextnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Call.
        /// </summary>
        public static string emergencycalltext {
            get {
                return ResourceManager.GetString("emergencycalltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Shouldn&apos;t Be Smaller Than Now.
        /// </summary>
        public static string EndDate_Now {
            get {
                return ResourceManager.GetString("EndDate_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Shouldn&apos;t Be Smaller Than Original End Date.
        /// </summary>
        public static string EndDate_Original {
            get {
                return ResourceManager.GetString("EndDate_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string enddatetext {
            get {
                return ResourceManager.GetString("enddatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Responsible Name.
        /// </summary>
        public static string enterresponsiblenametext {
            get {
                return ResourceManager.GetString("enterresponsiblenametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Task Name.
        /// </summary>
        public static string entertasknameplaceholder {
            get {
                return ResourceManager.GetString("entertasknameplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Completion Evedince.
        /// </summary>
        public static string EvedinceError {
            get {
                return ResourceManager.GetString("EvedinceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Evidence.
        /// </summary>
        public static string Evidence {
            get {
                return ResourceManager.GetString("Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string exisrcodeTitle {
            get {
                return ResourceManager.GetString("exisrcodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist Client.
        /// </summary>
        public static string ExistClient {
            get {
                return ResourceManager.GetString("ExistClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string existclienttext {
            get {
                return ResourceManager.GetString("existclienttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string existcodebtn {
            get {
                return ResourceManager.GetString("existcodebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Code .
        /// </summary>
        public static string existcoetext {
            get {
                return ResourceManager.GetString("existcoetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string failuretext {
            get {
                return ResourceManager.GetString("failuretext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string filenametext {
            get {
                return ResourceManager.GetString("filenametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string filestext {
            get {
                return ResourceManager.GetString("filestext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string filiterpoptitile {
            get {
                return ResourceManager.GetString("filiterpoptitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filtered date is not correct.
        /// </summary>
        public static string FilteredDateIncorrect {
            get {
                return ResourceManager.GetString("FilteredDateIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Employee.
        /// </summary>
        public static string findemployeetext {
            get {
                return ResourceManager.GetString("findemployeetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Forget {
            get {
                return ResourceManager.GetString("Forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string fromtext {
            get {
                return ResourceManager.GetString("fromtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Mode.
        /// </summary>
        public static string FullMode {
            get {
                return ResourceManager.GetString("FullMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullnametext {
            get {
                return ResourceManager.GetString("fullnametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someting Went Wrong! Please Contact Administration.
        /// </summary>
        public static string GeneralErorr {
            get {
                return ResourceManager.GetString("GeneralErorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string hidetext {
            get {
                return ResourceManager.GetString("hidetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string highenumtext {
            get {
                return ResourceManager.GetString("highenumtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree With .
        /// </summary>
        public static string Iagree {
            get {
                return ResourceManager.GetString("Iagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Have No Account .
        /// </summary>
        public static string IhaveNoAccount {
            get {
                return ResourceManager.GetString("IhaveNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Uploading Image.
        /// </summary>
        public static string imageuploadfilled {
            get {
                return ResourceManager.GetString("imageuploadfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string indicatorloadingtext {
            get {
                return ResourceManager.GetString("indicatorloadingtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string inProgressTask {
            get {
                return ResourceManager.GetString("inProgressTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string invailddate {
            get {
                return ResourceManager.GetString("invailddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More....
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Loading Error! Please Contact Administration.
        /// </summary>
        public static string loadTaskErorr {
            get {
                return ResourceManager.GetString("loadTaskErorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string logouttext {
            get {
                return ResourceManager.GetString("logouttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string lowenumtext {
            get {
                return ResourceManager.GetString("lowenumtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string NameOrEmail {
            get {
                return ResourceManager.GetString("NameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nametext {
            get {
                return ResourceManager.GetString("nametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string newClientText {
            get {
                return ResourceManager.GetString("newClientText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newpassplaceholder {
            get {
                return ResourceManager.GetString("newpassplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string newtasktitle {
            get {
                return ResourceManager.GetString("newtasktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files.
        /// </summary>
        public static string nofiletext {
            get {
                return ResourceManager.GetString("nofiletext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No History For This Task.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have No New Notifications.
        /// </summary>
        public static string NoNewNotificationsLabel {
            get {
                return ResourceManager.GetString("NoNewNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifications.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Employee .
        /// </summary>
        public static string noreassignlist {
            get {
                return ResourceManager.GetString("noreassignlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result For Search.
        /// </summary>
        public static string noresultsearch {
            get {
                return ResourceManager.GetString("noresultsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string normalenumtext {
            get {
                return ResourceManager.GetString("normalenumtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tasks Found!.
        /// </summary>
        public static string NoTasksFound {
            get {
                return ResourceManager.GetString("NoTasksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string notConnectedMsg {
            get {
                return ResourceManager.GetString("notConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notificationsettingtext {
            get {
                return ResourceManager.GetString("notificationsettingtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started .
        /// </summary>
        public static string notStartedTask {
            get {
                return ResourceManager.GetString("notStartedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported File!.
        /// </summary>
        public static string notSupportedFile {
            get {
                return ResourceManager.GetString("notSupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string oktext {
            get {
                return ResourceManager.GetString("oktext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string oldpasswordplaceholder {
            get {
                return ResourceManager.GetString("oldpasswordplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passwordtext {
            get {
                return ResourceManager.GetString("passwordtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        public static string phonenumberplaceholder {
            get {
                return ResourceManager.GetString("phonenumberplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phonenumbertext {
            get {
                return ResourceManager.GetString("phonenumbertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string Position_Validation {
            get {
                return ResourceManager.GetString("Position_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string positiontext {
            get {
                return ResourceManager.GetString("positiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string prioritytext {
            get {
                return ResourceManager.GetString("prioritytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profilesettingtext {
            get {
                return ResourceManager.GetString("profilesettingtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong Happened.Kindly, Retry.
        /// </summary>
        public static string progressnotupdatedtext {
            get {
                return ResourceManager.GetString("progressnotupdatedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have To Choose Project.
        /// </summary>
        public static string projectaletmessage {
            get {
                return ResourceManager.GetString("projectaletmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projecttext {
            get {
                return ResourceManager.GetString("projecttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Here To Re Assign Employee.
        /// </summary>
        public static string reaasigneetext {
            get {
                return ResourceManager.GetString("reaasigneetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please State Your Reason.
        /// </summary>
        public static string Reasonreq {
            get {
                return ResourceManager.GetString("Reasonreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess.
        /// </summary>
        public static string ReassignSucess {
            get {
                return ResourceManager.GetString("ReassignSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Sucessfully.
        /// </summary>
        public static string Reassignsucessmessage {
            get {
                return ResourceManager.GetString("Reassignsucessmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Assign.
        /// </summary>
        public static string ReassignText {
            get {
                return ResourceManager.GetString("ReassignText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string referencestext {
            get {
                return ResourceManager.GetString("referencestext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this task?.
        /// </summary>
        public static string RejectMsg {
            get {
                return ResourceManager.GetString("RejectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Task.
        /// </summary>
        public static string RejectTask {
            get {
                return ResourceManager.GetString("RejectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date Shouldn&apos;t Be Greater Than End Date.
        /// </summary>
        public static string ReminderDate_End {
            get {
                return ResourceManager.GetString("ReminderDate_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date Shouldn&apos;t Be Smaller Than Start Date.
        /// </summary>
        public static string ReminderDate_Start {
            get {
                return ResourceManager.GetString("ReminderDate_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date.
        /// </summary>
        public static string reminderdatetext {
            get {
                return ResourceManager.GetString("reminderdatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder Enabled.
        /// </summary>
        public static string reminderenabledtext {
            get {
                return ResourceManager.GetString("reminderenabledtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Change Due Date.
        /// </summary>
        public static string RequestChangeDueDate {
            get {
                return ResourceManager.GetString("RequestChangeDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong Happened.
        /// </summary>
        public static string RequestFail {
            get {
                return ResourceManager.GetString("RequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Has Been Successfully.
        /// </summary>
        public static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Successfully Modified Your Registration Password.
        /// </summary>
        public static string ResetMessageSucess {
            get {
                return ResourceManager.GetString("ResetMessageSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully.
        /// </summary>
        public static string ResetmessageTitle {
            get {
                return ResourceManager.GetString("ResetmessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username Or Email.
        /// </summary>
        public static string resetpalceholder {
            get {
                return ResourceManager.GetString("resetpalceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password Or Username.
        /// </summary>
        public static string resetpassfail {
            get {
                return ResourceManager.GetString("resetpassfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Resetpasstext {
            get {
                return ResourceManager.GetString("Resetpasstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string resetpasswordtext {
            get {
                return ResourceManager.GetString("resetpasswordtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Has Been Verified.
        /// </summary>
        public static string resetpasswordtext2 {
            get {
                return ResourceManager.GetString("resetpasswordtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string returnedTask {
            get {
                return ResourceManager.GetString("returnedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string returnedtext {
            get {
                return ResourceManager.GetString("returnedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Return To .
        /// </summary>
        public static string returnquestion {
            get {
                return ResourceManager.GetString("returnquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskname ,Employee Or Sector,...
        /// </summary>
        public static string saerchplaceholder {
            get {
                return ResourceManager.GetString("saerchplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskname ,Employee Or Department,...
        /// </summary>
        public static string saerchplaceholdertype2 {
            get {
                return ResourceManager.GetString("saerchplaceholdertype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string searchtitleplaceholder {
            get {
                return ResourceManager.GetString("searchtitleplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchtitletext {
            get {
                return ResourceManager.GetString("searchtitletext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sectortext {
            get {
                return ResourceManager.GetString("Sectortext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files....
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string selectPosition {
            get {
                return ResourceManager.GetString("selectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Priority.
        /// </summary>
        public static string selectpriority {
            get {
                return ResourceManager.GetString("selectpriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        public static string selectProject {
            get {
                return ResourceManager.GetString("selectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reference.
        /// </summary>
        public static string selectReference {
            get {
                return ResourceManager.GetString("selectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        public static string selectSource {
            get {
                return ResourceManager.GetString("selectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supporting Document.
        /// </summary>
        public static string SelectSupportingDocument {
            get {
                return ResourceManager.GetString("SelectSupportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User Group.
        /// </summary>
        public static string selectUserGroup {
            get {
                return ResourceManager.GetString("selectUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have To Enter Taskname.
        /// </summary>
        public static string serachnamemessage {
            get {
                return ResourceManager.GetString("serachnamemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showmore.
        /// </summary>
        public static string showmoretext {
            get {
                return ResourceManager.GetString("showmoretext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string showtext {
            get {
                return ResourceManager.GetString("showtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Here!.
        /// </summary>
        public static string SignUpHere {
            get {
                return ResourceManager.GetString("SignUpHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string sourcetext {
            get {
                return ResourceManager.GetString("sourcetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Shouldn&apos;t Be Smaller Than Now.
        /// </summary>
        public static string StartDate_Now {
            get {
                return ResourceManager.GetString("StartDate_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string startdatetext {
            get {
                return ResourceManager.GetString("startdatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Statustext {
            get {
                return ResourceManager.GetString("Statustext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submittext {
            get {
                return ResourceManager.GetString("submittext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Is Added Sucessfully.
        /// </summary>
        public static string taskaddedtext {
            get {
                return ResourceManager.GetString("taskaddedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        public static string taskDelayed {
            get {
                return ResourceManager.GetString("taskDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        public static string taskDetals {
            get {
                return ResourceManager.GetString("taskDetals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task History.
        /// </summary>
        public static string TaskHistory {
            get {
                return ResourceManager.GetString("TaskHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List.
        /// </summary>
        public static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List User Group.
        /// </summary>
        public static string TaskListUserGroub {
            get {
                return ResourceManager.GetString("TaskListUserGroub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Mode.
        /// </summary>
        public static string TaskMode {
            get {
                return ResourceManager.GetString("TaskMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string tasknametext {
            get {
                return ResourceManager.GetString("tasknametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task  Not Added Sucessfully.
        /// </summary>
        public static string tasknotadded {
            get {
                return ResourceManager.GetString("tasknotadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string totext {
            get {
                return ResourceManager.GetString("totext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TremsAndConditions {
            get {
                return ResourceManager.GetString("TremsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name should be unique.
        /// </summary>
        public static string UniqueTaskName {
            get {
                return ResourceManager.GetString("UniqueTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Again.
        /// </summary>
        public static string uploadagintext {
            get {
                return ResourceManager.GetString("uploadagintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Uploading.
        /// </summary>
        public static string uploadfileagaintext {
            get {
                return ResourceManager.GetString("uploadfileagaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Support.
        /// </summary>
        public static string urgentsupporttext {
            get {
                return ResourceManager.GetString("urgentsupporttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check This If The Task Needs An Urgent Support From.
        /// </summary>
        public static string urgentsupporttext2 {
            get {
                return ResourceManager.GetString("urgentsupporttext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One Of User Groups Or Positions.
        /// </summary>
        public static string UserGroup_Position_Validation {
            get {
                return ResourceManager.GetString("UserGroup_Position_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User Group.
        /// </summary>
        public static string UserGroup_Validation {
            get {
                return ResourceManager.GetString("UserGroup_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string usergrouptext {
            get {
                return ResourceManager.GetString("usergrouptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        public static string usernameplaceholder {
            get {
                return ResourceManager.GetString("usernameplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string usernametext {
            get {
                return ResourceManager.GetString("usernametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Way To Get Statrted Is To Quit Talking And Being Doing, Walt Desiny.
        /// </summary>
        public static string WaltDesinyLabel {
            get {
                return ResourceManager.GetString("WaltDesinyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcometext {
            get {
                return ResourceManager.GetString("welcometext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Credentials!.
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Username Or Password.
        /// </summary>
        public static string WrongUserOrPass {
            get {
                return ResourceManager.GetString("WrongUserOrPass", resourceCulture);
            }
        }
    }
}
